version: "3.9"

services:
  trino:
    image: trinodb/trino:latest
    ports:
      - 8080:8080
    container_name: trino
    environment:
      - JVM_MAX_HEAP_SIZE=2G
    volumes:
      - ./trino_etc:/etc/trino

  minioserver:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    container_name: minioserver
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
    volumes:
      - ./nessie_data:/var/lib/nessie

networks:
  default:
    name: iceberg_env
    driver: bridge

volumes:
  minio_data:
  trino_etc:
  nessie_data: